name: Docker

on:
  push:
    branches:
      - 'master'
  # Runs this workflow weekly (on monday)
  schedule:
    - cron: '0 0 * * 1'
  # Allows to run this workflow manually (from the Actions tab)
  workflow_dispatch:

jobs:

  repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        name: Search Dockerfiles
        id: dockerfiles
        run: |
          DOCKERFILES=( $(find . -not -path '*/.*' -type f -name Dockerfile | sort) )
          JSON="[$( printf -- '"%s",' "${DOCKERFILES[@]}" | sed 's/,$//' )]"
          echo "paths=$JSON" >> $GITHUB_OUTPUT
    outputs:
      dockerfiles: ${{ steps.dockerfiles.outputs.paths }}

  docker:
    needs: repository
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockefile: ${{ fromJson(needs.repository.outputs.dockerfiles) }}
    steps:
      - uses: actions/checkout@v3
      -
        name: Setup vars
        id: setup
        run: |
          function tuc {
            local stdin; read -d '' -u 0 stdin;
            echo "$stdin" | rev | cut $@ | rev
          }

          IMG_FILE=${{ matrix.dockefile }}
          echo "file=$IMG_FILE" >> $GITHUB_OUTPUT

          IMG_NAME=$( echo "${{ matrix.dockefile }}" | tuc -d "/" -f 3 )
          echo "name=$IMG_NAME" >> $GITHUB_OUTPUT

          IMG_TAG=$( echo "${{ matrix.dockefile }}" | tuc -d "/" -f 2 )
          echo "tag=$IMG_TAG" >> $GITHUB_OUTPUT
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ${{ steps.setup.outputs.file }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.setup.outputs.name }}:${{ steps.setup.outputs.tag }}
